apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloud-platform-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: cloud-native-cicd

  source:
    repoURL: https://github.com/KartikNaphade2004/cloud-native-cicd-eks.git
    targetRevision: main
    path: k8s/overlays/prod

  destination:
    server: https://kubernetes.default.svc
    namespace: cloud-platform

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 2m
